name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: gluttonousolingo
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Metadata action
      uses: docker/metadata-action@v4.0.1
      id: meta
      with:
        images: |
          gluttonousolingo/jsonnet-bundler
        tags: |
          latest
          type=sha
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        tags: ${{ steps.meta.outputs.tags }}
        push: true
